### PR TITLE
Get rid of Volley

### PR DESCRIPTION
**Pull request by daniloercoli**
This PR gets rid of Volley network lib, and switches back to the native HttpURLConnection.

Getting rid of Volley we should see low memory consumption, and better performances. We don't need to use Volley to make a simple POST request to the server. Volley adds nice features to the networking layer, but a bit of overkill for this project. Memory consumption and overall performance are better with HttpURLConnection for the kind of network connection we have in this prj (single connection, no pooling is require, no tagging of connection required, etc).

### CODE REVIEW

**Comment by daniloercoli** [comment]
//cc @astralbodies @maxme

**Comment by astralbodies** [comment]
> Showing  4 changed files  with 170 additions and 269 deletions.
Music to my ears.

Functionally this is in line with what I did with the iOS client - tried to use base libraries/frameworks as much as possible.

**Comment by maxme** [comment]
` mQueue = Volley.newRequestQueue(ctx);` can be removed

**Comment by maxme** [comment]
Volley dependency should be removed in the `build.gradle` file

```
dependencies {
    compile 'com.mcxiaoke.volley:library:1.0.15'
}
```

**Comment by maxme** [comment]
PR looks fine, we just need to remove the gradle dependency before the merge.

**Comment by daniloercoli** [comment]
Removed the gradle dependency and got rid of unused variables.

**Pull request merged**
